#!/bin/bash
#
# Run the simulator
# An optional argument trafficCondition can be provided
#
# ./run <trafficCondition>
#
# Which can be one of
# + lowTraffic
# + moderateTraffic
# + highTraffic
#
java trafficsim.core.Main "$@"